import { Footer } from "../footer/Footer";
import Head from "next/head";
import { MainBanner } from "../banner/mainbanner";
import Navbar from "../nav/Navbar";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Madyan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  );
}
